import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'src/app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  runApp(App());
  //TODO
  // IMPROVE AUTH SCREEN UI
  // ADD TWO FACTOR AUTH
  // USER MUST BE REGISTERED WITH INFO?, AND THEN CHOOSE SHOP SCREEN, AND THEN HOME SCREEN WITH THAT SHOP ITEMS
  // ADD NEW SCREEN TO GET USER INFO, PAYMENT INFO BEFORE TRANSACTION, AND CHOOSE STORE TOO? WITH STEPPER?
  // ADD MORE USER INFO, ADDRESS, RECENTLY SELECTED STORES, DEFAULT STORES ETC
  // ADD CHOOSE STORE SCREEN? FROM CURRENT LOCATION, YOUR LIST, OR SEARCH
  // ADD DRAWER TO HOME SCREEN? OR NOMAL BOTTOM NAV TAB WITH USER INFO TAB
  // SEARCH ON APPBAR ACTION
  // TOP: CAROUSEL SLIDER WITH ADVERTISEMENT BOTTOM: TODAY'S RECOMMENDATION WITH SLIVERAPPBAR
  // STAGGERED GRID VIEW FOR TODAY'S RECOMMENDATION UI?
  // PHOTO, NAME, REGULAR PRICE, DISCOUNT PRICE, CODE
  // PRODUCT DETAIL SCREEN WITH INSTORE MAP AND ADD TO CART, NOTIFY PLEASE MAKE SURE TO ADD YOUR OWN CART TOO
  // FLUSHBAR SNACKBAR
  // ADD FLUTTER BARCODE SCAN
  // TWO FACTOR AUTH?
}
