import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'src/app.dart';

void main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await SystemChrome.setPreferredOrientations([DeviceOrientation.portraitUp]);
  runApp(App());
  //TODO
  // ADD FIREBASE OR BACKEND
  // ADD REGISTRATION SCREEN, AUTH INFO, USER INFO, AND PAYMENT INFO WITH STEPPER
  // ADD CHOOSE SHOP SCREEN FROM CURRENT LOCATION, YOUR LIST, OR SEARCH
  // USER MUST BE REGISTERED WITH INFO, AND THEN CHOOSE SHOP SCREEN, AND THEN HOME SCREEN WITH THAT SHOP ITEMS
  // ADD DRAWER TO HOME SCREEN? OR NOMAL BOTTOM NAV TAB WITH USER INFO TAB
  // SEARCH ON APPBAR ACTION
  // TOP: CAROUSEL SLIDER WITH ADVERTISEMENT BOTTOM: TODAY'S RECOMMENDATION WITH SLIVERAPPBAR
  // STAGGERED GRID VIEW FOR TODAY'S RECOMMENDATION UI?
  // PHOTO, NAME, REGULAR PRICE, DISCOUNT PRICE, CODE
  // PRODUCT DETAIL SCREEN WITH INSTORE MAP AND ADD TO CART, NOTIFY PLEASE MAKE SURE TO ADD YOUR OWN CART TOO
  // FLUSHBAR SNACKBAR
  // ADD FLUTTER BARCODE SCAN
  // TWO FACTOR AUTH?
}
